# Generated by Django 3.0.4 on 2020-05-20 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_title', models.CharField(max_length=100)),
                ('serial_id', models.CharField(max_length=3)),
                ('seller_title', models.CharField(max_length=100)),
                ('invoice_series', models.CharField(max_length=10)),
                ('buyer_code', models.CharField(max_length=100)),
                ('date_bought', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('commissioners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('responsible_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_type', models.CharField(choices=[('VNT', 'vnt.'), ('KOMPL', 'kompl.')], default='VNT', max_length=5)),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('sum', models.FloatField()),
                ('reason', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.MaterialAct')),
            ],
        ),
    ]
