# Generated by Django 3.0.4 on 2020-05-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_materialact_serial_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialact',
            old_name='seller_title',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='materialact',
            old_name='buyer_code',
            new_name='sellers_code',
        ),
    ]
