# Generated by Django 3.0.4 on 2020-05-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200521_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='amount_type',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('SET', 'Set')], default='PIECE', max_length=5),
        ),
    ]
