# Generated by Django 3.0.4 on 2020-05-20 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_materials_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='forms.MaterialAct'),
        ),
    ]
